export const INVALID_PHONE_NUMBER_CODE = 422;
export const EXISTING_PHONE_NUMBER_CODE = 400;
export const SUCCESS_REGISTER_CODE = 200;
export const SUCCESS_LOGIN_CODE = 200;
export const WRONG_PASSWORD_CODE = 403;
export const NON_EXISTING_PHONE_NUMBER_CODE = 404;
